### ISSUE TITLE
Integrate the Restcomm Statistics

### ISSUE THREAD

**Issue by SergeyLee** [Mobicents/jain-slee.sip#34]
First step: to integrate the Restcomm Statistics in SIP RA only.
Second step: to integrate the Restcomm Statistics as JSLEE Core facility (that all RAs can get and increment either calls, seconds or/and messages yes so that each RAs doesn't have to instantiate their own RestcommStatsReporter).

**Comment by jaimecasero** [comment]
Ideally we should reuse SLEE Usage facility and expose all of them through JMX. So an eventual JXM adaptor could be implemented to send statistics to Restcomm server. Lets try not to include this into jslee or RA core in a propietary way... 

refer to spec 

- 11.2.7   Resource Adaptor Usage Parameters interface deployment de-scriptor 
- 11.4.3   Resource adaptor entity access to a usage parameter set

**Comment by SergeyLee** [comment]
@jaimecasero what did you mean by "eventual JMX adaptor"? Did you mean some Statistics RA (Resource Adaptor) or something SLEE internal?
Now I am investigating ResourceManagementImpl for implementing RestComm Statistics logic.

**Comment by jaimecasero** [comment]
I meant that once we expose proper counters through standard SLEE Usage mbeans, we may create a separate WAR deployment that takes those counters and publish them to Telestax servers,instead of doing that inside the SLEE core

**Comment by SergeyLee** [comment]
@jaimecasero Why we cant do this inside the SLEE core? Why we need external WAR deployment and why WAR?

**Comment by jaimecasero** [comment]
@SergeyLee  of course we can do it in SLEE core, is a design choice. 

My point is, the fact we expose the traffic counters/samples through SLEE standard Usage MBeans, makes it kind of natural to consume the Usage JMX API from an external application, making the statistics report optional by deployment (instead of configuration). 

Another point is that, counter/samples are usually aggregated by time intervals periodically, and one important step on counter/samples aggregation/harvesting is the periodic reset of those (check resetAllUsageParameters in Spec). If the harvesting is done internally in our SLEE impl, and some customer likes to reuse the UsageMbean, both monitoring processes will overried each other with unexpected statistics results. Of course, the statistics reporting can be made optional by slee configuration, but i think is simply cleaner to have it as an external module...

**Comment by satanatoly** [comment]
Integrated. Closing
